### ISSUE TITLE
Crash: Duplicate Entity Listener

### ISSUE THREAD

**Issue by Sunekaer** [MaxNeedsSnacks/roadrunner#12]
### Expected Behavior
To not crash

### Actual Behavior
Crashed after player slept

### Reproduction Steps
Random happens

### Attachments
https://pastebin.com/ZHfdNrb8

**Comment by TheAdamizer** [comment]
This is an issue seen in Single Player worlds, making them unload-able until RoadRunner is removed.

AKA: Bump

**Comment by MojangPlsFix** [comment]
Can confirm the issue on Multiplayer. Only way to fix it, is to remove the mod.
https://paste.myftb.de/pamadojuze.kotlin

**Comment by Reshy** [comment]
Having this issue as well.

**Comment by MaxNeedsSnacks** [comment]
Ater putting in a bit of thought, I remember Forge pretty much always having duplicate entity issues since **all** the way back in 1.5.2, and since the thing that seems to be crashing is entities getting added to trackers when they're added into the world, this *might* be related to that? Unfortunately other than that, I'm as lost on this one as you guys are, but I'll try to find a way to hopefully reproduce this reliably. Until then, feel free to disable the `mixin.ai.nearby_entity_tracking` rules since they're the ones breaking here

**Comment by MaxNeedsSnacks** [comment]
I've mentioned it in #30 already, but if anyone here is willing out to help (and still has the "broken" world): Could you perhaps send me your save file for further debugging? Trying to look for leads but I'm coming up with nothing good at the moment unfortunately :/

**Comment by NighthowlerStudios** [comment]
I have a save file here but it's on a multiplayer server.  my friend's client was disconnected when a wolf's entity tracker was attempted twice after finding a dungeon.

Opening the world requires Kaleidio's Battle Pack 4.3.6 to be installed.  Note that if the crash occurs on a multiplayer server, players can rejoin without issue

[crash-2022-06-27_14.48.54-client.txt](https://github.com/MaxNeedsSnacks/roadrunner/files/8992171/crash-2022-06-27_14.48.54-client.txt)

warning, it is a large world due to lots of chunks having been generated.  you may not have the crash again whilst this occurs. 

https://drive.google.com/file/d/1pjJbwgp_VfLRQ1ujGLQY6k1_I4GfP9Oz/view?usp=sharing

**Comment by embeddedt** [comment]
As of RoadRunner 1.5.0, the problematic optimization is disabled by default, as I suspect Forge entity tracking is too broken for it to work well, and it reduces performance in normal worlds anyway.
