### ISSUE TITLE
crash when trying to entering in nether

### ISSUE THREAD

**Issue by TheYoloPanda** [MaxNeedsSnacks/roadrunner#26]
1. Enter in the nether

[crash-2021-10-31_23.15.33-server.txt](https://github.com/MaxNeedsSnacks/roadrunner/files/7449880/crash-2021-10-31_23.15.33-server.txt)

**Comment by TheYoloPanda** [comment]
[All The Nodes-0.0.3-Preview.zip](https://github.com/MaxNeedsSnacks/roadrunner/files/7449886/All.The.Nodes-0.0.3-Preview.zip)

This crash happens in my modpack, all the nodes. 

https://pste.ch/xuvudowubo.cs

*minified because it was over 2000 characters*

**Comment by MaxNeedsSnacks** [comment]
Can you reliably reproduce this with RoadRunner installed? I've never seen this crash before, so this is a bit odd. Also can you try and see whether it still crashes (a) without Cave Biome API and (b) without RoadRunner installed?

**Comment by TYPyz** [comment]
I'm going to test if it crashes without roadrunner installed, but since cave biome API has not beeing updated I don't think is cave biome api's fault. Also in the 0.0.2 version of my modpack which have an older version of roadrunner and the same version of cave biome api, going to the nether didn't cause crashes.

**Comment by TheYoloPanda** [comment]
Ok it keep crashing even after removing roadrunner, my bad. Sorry for wasting your time

**Comment by MaxNeedsSnacks** [comment]
No worries, the logs *did* kind of make it look like it was RR's fault ^^
