### ISSUE TITLE
incompatibility with EnderMail mod

### ISSUE THREAD

**Issue by JetpackRescue** [MaxNeedsSnacks/roadrunner#34]
### Expected Behavior
In the EnderMail mod, you can send packages to a specific xyz coor or to a named locker. So you can send items back to a locker at your base, or to a friends locker.

### Actual Behavior
With Roadrunner installed, the packages in EnderMail always get sent to a coord of around -1, 70, -1. Then the next package you send gets sent to -1, 71, -1 and so on, stacking up in the world.. The package does not get sent to the locker, but always to these coordinated. Entering coordinates as the packages destination ends with the same behavior.

### Reproduction Steps
Install Road Runner and EnderMail, place locker on ground, right click and name it. place a package on the ground, right click the package with a stamp in your hand, enter the name of the locker you want the package sent to, click done. Then right click the package with a Package Controller and an enderman shows up and takes the package, but delivers it to the wrong place.

I really need both mods for my modpack.

**Comment by malte0811** [comment]
The issue seems to be [this code](https://github.com/MattCzyr/EnderMail/blob/6450e041b5528e18c90e0057d8ae6d5da36e4aa3/src/main/java/com/chaosthedude/endermail/blocks/PackageBlock.java#L290-L296) in EnderMail, or at least that code is causing an exception in RR. I've never seen this pattern before, I'll do some testing to see if it's actually necessary on 1.16 later.

**Comment by MaxNeedsSnacks** [comment]
Fixed in EnderMail by malte's PR, thanks for reporting!
