### ISSUE TITLE
Crash with Buddycards

### ISSUE THREAD

**Issue by kerokeropippi** [MaxNeedsSnacks/roadrunner#38]
### Reproduction Steps
Crash when put Buddysteel Vault.

### Crash Report File
https://gist.github.com/kerokeropippi/0a979cc3fcda8275eec1cb511edc002c

**Comment by SkullDiamond** [comment]
I'm having the same problem whit the Buddysteel Vault

**Comment by MaxNeedsSnacks** [comment]
RoadRunner's `BlockEntityList` does not allow adding the same BE twice (this allows us to treat the "list" more like a set with insertion order), and whatever Buddycards is doing seems to be breaking that assumption since they attempt to call `setTileEntity` manually here. For now, you can fix the issue by disabling the `mixin.world.block_entity_ticking.collections` rule in your rule overrides, since unfortunately, I doubt this is going to be fixed on our end (mostly because 1.16 support is winding down, and neither me nor malte have particularly much time to work on this mod right now)
