### ISSUE TITLE
[1.16.5] VMP features (a fabric mod) - server optimizer for large player counts.

### ISSUE THREAD

**Issue by Cixon** [MaxNeedsSnacks/roadrunner#40]
~~Is your feature request related to a problem? Please describe.~~
**Disclaimer:** I'm not 100% aware of ALL the features/mixins Roadrunner offers but I'm partially cognizant.

**Link(s):**
https://www.curseforge.com/minecraft/mc-mods/vmp-fabric
https://github.com/RelativityMC/VMP-fabric/blob/ver/1.18/LICENSE

Very Many Players uses distance maps to optimize things like spawn checks, there's optimizations to high entity count targeting and a variety of other micro optimizations as well. Now, I'm sure Roadrunner has a handful of these features already but I'd love if RR could integrate some of the features it doesn't have.

**Describe alternatives you've considered**
N/A.

**Additional context**
I understand this mod is still in early development and I'm willing to wait for a stable release.

**Comment by MaxNeedsSnacks** [comment]
From what I can tell, there is no 1.16 version of VMP out at the time of writing this, and I'm assuming the author has no plans to make one, either. Since RoadRunner right now is based on the 1.16 builds of Lithium, and I can't be sure that any of their optimisations actually work for Minecraft 1.16, **especially** since we have to work with / around Forge patches as well, I'm gonna be holding off on this for now, sorry
