### ISSUE TITLE
[1.16.5] [1.1.1] Add compat support for Simply Improved Terrain

### ISSUE THREAD

**Issue by Cixon** [MaxNeedsSnacks/roadrunner#5]
**Is your feature request related to a problem? Please describe.**
With roadrunner installed, the server/client won't launch due to an error.

### Latest Log (ln 100):
[latest.log](https://github.com/MaxNeedsSnacks/roadrunner/files/7272216/latest.log)

[main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: **Redirector handleNoiseSample(Lnet/minecraft/world/gen/SimplexNoiseGenerator;II)F** in roadrunner.mixins.json:gen.fast_island_noise.TheEndBiomeSourceMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap RoadRunner-mc1.16.5-refmap.json

**Mod in question**
[Simply Improved Terrain](https://www.curseforge.com/minecraft/mc-mods/simply-improved-terrain)

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Comment by MaxNeedsSnacks** [comment]
We will not be adding explicit compatibility for Simply Improved Terrain's end generation since they completely overwrite vanilla behaviour, invalidating our own optimisations in the process. You can fix this by adding a rule `mixin.gen.fast_island_noise=false` to your rule config, or asking the SIT devs to add a rule themselves as they've already done on [Fabric](https://github.com/KdotJPG/Simply-Improved-Terrain/blob/Fabric-1.16/src/main/resources/fabric.mod.json) (see this [wiki page](https://github.com/MaxNeedsSnacks/roadrunner/wiki/Configuration-Files#rule-overrides) for instructions on how to do this for RoadRunner)
