### ISSUE TITLE
[Non Issue] Incompat with Performant

### ISSUE THREAD

**Issue by Speiger** [MaxNeedsSnacks/roadrunner#56]
o/ Long time no see.

Coming from my testserver. I remembered your mod when we started playing again,
And thought since we deal with lag issues. Lets try out Road runner and see its magic.

Eh yeah infinite crash loop until performant was deinstalled.

To me a non issue since they add things I can not agree with anymore.

I will report back how the performance difference is compared to performant.

**Comment by MaxNeedsSnacks** [comment]
Yeah, issues with Performant have been known ever since the first Forge-centric Lithium fork has surfaced a couple of months ago. I've closed any other issues referring to this since I thought CF would report it on their own in the app (I did mark the two as incompatible there), but it might be important having this be out there for end users wanting to use both still, so I've pinned your issue for now to leave it up as a heads-up (and to avoid anymore duplicates of this since we've been having these pop up quite literally since issue #2)

**Comment by Speiger** [comment]
Yeah thats fine. I created this just to let you know if that was a case.
I already noticed a couple issues with Roadrunner I will report back, nothing crash related but stuff you might want to know.
But I will compile a list that you will get by the end of a month.

So far just tiny stuff that should be pretty easily addressed in 1 patch.
