### ISSUE TITLE
Small mixin error in 1.16.5

### ISSUE THREAD

**Issue by Speiger** [MaxNeedsSnacks/roadrunner#60]
When installing roadrunner on a server this error shows up.
Its only a log no crash but it should maybe be addressed.

[16:01:29] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/renderer/texture/TextureAtlasSprite for invalid dist DEDICATED_SERVER
[16:01:29] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/renderer/texture/TextureAtlasSprite for invalid dist DEDICATED_SERVER

Only issue i found so far with roadrunner. Loving the mod FYI.

**Comment by CamIsHereRN** [comment]
Same thing happens for a server that I'm on too. No crash log, but server doesn't start up. 

![image](https://user-images.githubusercontent.com/96709522/160219578-6a41c6e2-9e8c-4f8f-a1ec-8ce3c009bfbb.png)

The file that I am looking at is a debug.log file, so there's a bit more after that. 

![image](https://user-images.githubusercontent.com/96709522/160219644-4dad9cbf-547e-4c60-a865-80ee3ae6301b.png)
![image](https://user-images.githubusercontent.com/96709522/160219659-deafbb80-da1b-4215-8a48-15b0b8c0848b.png)

There is more, but it's pretty much almost all Dynamic Trees, or compat with other mods such as Quark and Oh the Biomes You'll Go.

**Comment by CamIsHereRN** [comment]
The Server isn't running Vanilla, so there might be some differences. The server does not start up.

**Comment by Speiger** [comment]
Yeah mine isn't crashing. But the solution is fairly simple, just move said mixin to the client only section

**Comment by MaxNeedsSnacks** [comment]
> just move said mixin to the client only section

The thing is, this mixin isn't related to any client-side code, if you look at the Logger, it's related to AI PathNodes.

The "issue" here is that we need to check whether a specific method from IForgeBlock has been overridden in a given subclass, which doesn't seem to be possible without looking at *all* of the declared methods (even getDeclaredMethod loads all of them before trying to find the one you're looking for), and **that** causes lookups of certain client-only classes through methods that involve, say, rendering code.

Forge does strip client-only code at runtime using ASM, however from what I can tell it only does so to methods *explicitly* annotated with @​OnlyIn, and doesn't remove the overrides of such methods (though that said I haven't really focused on this issue for a couple of months so my information may be off here). As using @​OnlyIn within mods is something Forge explicitly **does not** want you to do, we can't really fault the modders here either, and have chosen to just accept this as "broken" and not override any behaviour if we do encounter this sort of error.

Also, we explicitly catch these errors so that crash is **definitely** not related to RR, or at least, not related at all to the "error" messages you sent
