### ISSUE TITLE
[1.16.5] Incompatibility with Supplementaries mod 

### ISSUE THREAD

**Issue by Subthy** [MaxNeedsSnacks/roadrunner#62]
### Expected Behavior
Well server not to crash?

### Actual Behavior
Server crashed when chunks loaded in with supplementary mod ropes/rope knots . We needed to disable 

mixin.world.block_entity_ticking=false
mixin.world.chunk_access=false

, but now the server is running very slow, the TPS is good, but the chunk loading is really like really slow.

### Reproduction Steps
Place supplementary mod ropes on any stone walls, so it forms a knot and then unload the chunk and load it back in, if that happens maybe exit the world and load back in, as there was a server restart between the placement of ropes and the issue.

### Attachments
[crash-reports_crash-2022-03-16_15.29.09-server.txt](https://github.com/MaxNeedsSnacks/roadrunner/files/8362172/crash-reports_crash-2022-03-16_15.29.09-server.txt)

**Comment by MaxNeedsSnacks** [comment]
This is likely not an issue with RoadRunner and Supplementaries interacting directly; there seems to be some sort of deadlock in our `getChunk` method (perhaps related to the light engine? I recall seeing something like that on the original Lithium tracker), which I'm still trying to find the root cause of, but it would probably have to be outside of this issue specifically since it occurs to appear sporadically no matter what people actually end up doing in the world.
