### ISSUE TITLE
Entity class couldn't be analyzed

### ISSUE THREAD

**Issue by BloodyNecroZ** [MaxNeedsSnacks/roadrunner#63]
### Expected Behavior
This not to show on the console.

### Actual Behavior
This error shows up on console, and seems to be related to an Armored Pillager, from Dungeons Mobs mod. Possible incompatibility with said mod?

### Reproduction Steps
It happened randomly when my player character was AFK. This was the first time I've seen this.
I've noticed that spawning said mob with its specific egg on Creative mode also throws the error, as well as being near it.

### Attachments
![image](https://user-images.githubusercontent.com/40871880/163222307-518c723b-a1f2-459d-aeaa-1ea2dd552a45.png)

**Comment by MaxNeedsSnacks** [comment]
Not an issue, this is just a warning to the user that we can’t do anything here because we can’t prevent that client only code from being loaded (also please update the mod, this has been downgraded to a DEBUG message and the warning no longer „blames“ the other mod, when really, neither of us is really at fault)
