### ISSUE TITLE
Lag on single player??

### ISSUE THREAD

**Issue by lSherozl** [MaxNeedsSnacks/roadrunner#65]
### Expected Behavior
The game to run more smoothly with roadrunner
### Actual Behavior

Replace this text with what actually happened.
Lots of lag in single player

Okay so I ran a spark profiler and it seems this mod is second in terms of causing lag, if you don't mind reading this spark and letting me know what is causing the lag in single player https://spark.lucko.me/X6dV4ZxJ8x

**Comment by MaxNeedsSnacks** [comment]
The reason RoadRunner comes second here is because it either outright replaces or injects to a **lot** of vanilla code, to the point where it will actually be blamed for a lot of "lag" related to vanilla code (for example, the top "offender" here is related to block collisions). Most of these are perfectly normal contributions to tick time, though the `getChunk` calls in there seem to be... awfully slow, which _may_ be on our end, but should be investigated separately
