### ISSUE TITLE
Actual Crash on Startup

### ISSUE THREAD

**Issue by Drakoflame** [MaxNeedsSnacks/roadrunner#7]
Hey! Long time no see! Just updated to the latest version (1.2.1), and go ANOTHER crash on startup! This time a PROPER crash!
Log is follows:
https://pastebin.com/s2M4XqT5

Debug (different site because the log is more than the 256kb on pastebin.com):
https://pastebin.pl/view/16bf7aab

**Comment by MaxNeedsSnacks** [comment]
This... seems to be an external issue with Architectury Loom, I think (slash hope)?

Either way, I think it's an issue with the refmap remapper targeting the base class for this method rather than WorldChunk (Chunk in MCP), which... I could swear we had this exact issue before...

cc @shedaniel @Juuxel perhaps

**Comment by Drakoflame** [comment]
Am I using the right version? Or is that completely separate to the crash?

**Comment by MaxNeedsSnacks** [comment]
Nope you're fine, this is an issue with the toolchain I'm using :/

**Comment by MaxNeedsSnacks** [comment]
I won't be able to fix this until tomorrow unfortunately, you'll have downgrade to 1.1.1 until then and disable BE sleeping with `mixin.world.block_entity.sleeping=false` in your rule config I'm afraid :/

**Comment by MaxNeedsSnacks** [comment]
I downgraded Loom for a little bit, but it doesn't seem like GH Actions wants to *work* right now, so this might still take a couple of minutes :/
