### ISSUE TITLE
Failed to save Chunk

### ISSUE THREAD

**Issue by EdoEquin0x** [MaxNeedsSnacks/roadrunner#73]
### Expected Behavior
To work.

### Actual Behavior
Chunk don't seem to be saved, when Roadrunner is installed and running on a mohist server, the console is spammed with "Failed to save chunk" errors. 
After further investigations it seems that the mod is trying to cast tile entities to the entity class. The issue dissapear when removing roadrunner and happens with vanilla AND modded tile entities.

### Reproduction Steps
Simply using the mod with mohist.
You can eventually try with some other popular mods like Ice and Fire, Spartan Weaponry, AttributeFix, Better villages etc...

### Attachments
Some hastebins of the said error message
I also would like to point out the fact that the issue happens not only with Mohist, but with classic forge, with catserver, with magma and every single server api that can run mods you could possibly think of. So I don't think the server api is involved.

https://www.toptal.com/developers/hastebin/ofutozagil.css
https://www.toptal.com/developers/hastebin/ifaqopemeh.css
https://www.toptal.com/developers/hastebin/kovovinine.css

**Comment by MaxNeedsSnacks** [comment]
Mohist as well as any other implementations of Bukkit, Spigot or Paper are unsupported as Bukkit replaces core parts of the serverside infrastructure, some of which RoadRunner almost definitely relies on. If you could send me a **full mod list and log** of this happening on a standard Forge-modded server with no external APIs, feel free to reopen this issue, but otherwise, I can't really help much here unfortunately
