### ISSUE TITLE
New maintainer - can we please receive a 1.20.1 port?

### ISSUE THREAD

**Issue by Cixon** [MaxNeedsSnacks/roadrunner#83]
Any chance we could see this for 1.20.1 (neo)forge? saw [embeddedt](https://legacy.curseforge.com/members/embeddedt) took over for the 1.19 version, would be a neat port to see!

(radium reforged underperforms and has a slew of mod-incompatibilities) 🥲

**Comment by embeddedt** [comment]
This probably won't happen unless Radium drops support for 1.20.1 prematurely and I have time to take it over. The 1.19 version of Roadrunner is a backport of Radium 1.20, and I usually send patches to them nowadays if I find an obvious bug. Actually, the only main reason I published this backport to begin with is because someone asked for it so they could use it in their modpack without going through CF review hassle.

As for Radium underperforming, this is hard to quantify unless there is data showing it performs worse than Lithium on the same MC version, since with mods installed, lag is often exacerbated by their code, not vanilla code.
